---
openapi: 3.0.0
info:
  title: Get Stats API
  description: This API receives input from front end website where users input the stock number
  contact:
    email: nlai15@my.bcit.ca
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
tags:
- name: gym 
  description: tracking gym usage
paths:
  /health_status: 
    get: 
      summary: Gets the health status
      operationId: app.get_health
      description: Gets health of services
      responses: 
        '200': 
          description: Successfully returned health status
          content: 
            application/json: 
              schema: 
                type: object 
                items: 
                  $ref: '#/components/schemas/healthStats' 
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
components:
  schemas:
    healthStats: 
      required: 
      - receiver
      - storage
      - processing
      - audit
      - last_updated   
      properties: 
        receiver: 
          type: string 
          example: Running
        storage: 
          type: string 
          example: Running
        processing: 
          type: string 
          example: Running
        audit: 
          type: string 
          example: Down
        last_updated:
          type: string
          example: '2022-02-12 16:35:17.839066'